name: GH Actions

on:
  release:
    types: [published]
  push:
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-13  # Intel
          - os: macos-14 # Apple Silicon
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
        with:
          arch: amd64
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Build wheels
        run: |
          python -m pip install --upgrade meson ninja
          meson setup build
          ninja -C build
          ninja -C build test

