name: Tests Linux with coverage

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: build and tests with coverage
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip lcov g++
          pip install --upgrade meson ninja
      - name: Configure with meson
        run: meson -Db_coverage=true -Dwith_tests=true . build
      - name: Build (meson)
        run: ninja -C build
      - name: Run tests (meson)
        run: ninja test -C build
      - name: Generate Coverage report
        run: |
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --remove coverage.info '*/subprojects/*' --output-file coverage.info
          lcov --list coverage.info
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.info
